### ISSUE TITLE
[1.2.0] Quest migration not working properly

### ISSUE THREAD

**Issue by WhitePhant0m** [MaxNeedsSnacks/FTBQImporter#16]
Trying to migrate quests in manufactio seems to not work properly, some tasks require "missing items"
and after manually fixing them, trying to import progress gives this error
[22:28:32] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: ftbq_import progress

java.lang.NullPointerException: null
	at dev.maxneedssnacks.ftbqimporter.CommandImport.importProgress(CommandImport.java:583) ~[CommandImport.class:?]
	at dev.maxneedssnacks.ftbqimporter.CommandImport.execute(CommandImport.java:80) ~[CommandImport.class:?]
	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.util.Util.runTask(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by WhitePhant0m** [comment]
![image](https://user-images.githubusercontent.com/33400200/98742194-aab5e700-23b6-11eb-9887-8429d5617dc3.png)
This is what i mean by missing items
This is how it imported it {id:"itemfilters:missing",Count:1b,tag:{item:{id:"thermalfoundation:coin",Count:2000,Damage:98}},Damage:0s}

**Comment by MaxNeedsSnacks** [comment]
Do you have a full log file by any chance? This looks like something that SHOULD have been fixed already

**Comment by WhitePhant0m** [comment]
latest or debug?
also, for quest import or progress import?

**Comment by MaxNeedsSnacks** [comment]
Either will do, but I think debug might be more helpful here ^^

**Comment by WhitePhant0m** [comment]
[debug.log](https://github.com/MaxNeedsSnacks/FTBQImporter/files/5521128/debug.log)
this one has the quest progress import in it, will soon send one with quest import

**Comment by WhitePhant0m** [comment]
[quests.zip](https://github.com/MaxNeedsSnacks/FTBQImporter/files/5521306/quests.zip)
[debug.log](https://github.com/MaxNeedsSnacks/FTBQImporter/files/5521307/debug.log)
Here are the quests and debug log that has the quest import

**Comment by MaxNeedsSnacks** [comment]
https://github.com/MaxNeedsSnacks/FTBQImporter/blob/216ff5d900c99825cda2ab8d7bedcc5f4e51c340/src/main/java/dev/maxneedssnacks/ftbqimporter/CommandImport.java#L583

One of the owners of your BQ party/-ies hasn't connected since you've added FTB Library to your modpack. I'll probably fix this by adding a failsafe that sets a random party player as the owner if the latter isn't available

**Comment by MaxNeedsSnacks** [comment]
Could you see whether this jar fixes your problem?

[FTBQImporter-forge-1.12.2-2.0.0.jar](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-importer/files/3178913)

**Comment by MaxNeedsSnacks** [comment]
Closing this because I've chosen to release 2.0 publicly now.
If that version didn't fix your issue feel free to reopen ^^
