### ISSUE TITLE
Unable to import BQ to FTB Quests

### ISSUE THREAD

**Issue by Zanthyn** [MaxNeedsSnacks/FTBQImporter#6]
I get the following error when I type "/ftbq_import quests"
It cleared my old quests out but it did not import the quests from BQ.

![image](https://user-images.githubusercontent.com/20820060/72225208-55b40500-3548-11ea-84be-6b4f0416c5a6.png)

**Comment by MaxNeedsSnacks** [comment]
Hey, do you have a log file so I can see the error in more detail?

**Comment by Zanthyn** [comment]
I found the issue. I was trying to import quests from another modpack. I had to go back to the original modpack and convert it to FTB Quests then bring those over the new modpack for them to work. There were items missing between the two packs. I was trying to skip a bunch of manual work on my part.

**Comment by Zanthyn** [comment]
Here was the error I was getting just for reference.

[18:07:29] [Server thread/WARN]: Couldn't process command: ftbq_import quests
java.lang.NoSuchMethodError: com.feed_the_beast.ftbquests.quest.ServerQuestFile.newID()I
	at dev.maxneedssnacks.ftbqimporter.CommandImport.importQuests(CommandImport.java:143) ~[CommandImport.class:?]
	at dev.maxneedssnacks.ftbqimporter.CommandImport.func_184881_a(CommandImport.java:85) ~[CommandImport.class:?]
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:85) ~[CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by Zanthyn** [comment]
Well disregard my previous comment. I added FTB Quests and FTB Quest Importer to the modpack I was trying to pull quests from and I'm still getting the same error.

[18:28:23] [Server thread/WARN]: Couldn't process command: ftbq_import quests
java.lang.NoSuchMethodError: com.feed_the_beast.ftbquests.quest.ServerQuestFile.newID()I
	at dev.maxneedssnacks.ftbqimporter.CommandImport.importQuests(CommandImport.java:143) ~[CommandImport.class:?]
	at dev.maxneedssnacks.ftbqimporter.CommandImport.func_184881_a(CommandImport.java:85) ~[CommandImport.class:?]
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:83) ~[CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by Zanthyn** [comment]
Sorry for all the spam. Updating to latest versions of FTB Library, FTB Utilities, and FTB Quests seems to have resolved the issue. Quests are successfully in FTB Quests now and working as intended.

**Comment by MaxNeedsSnacks** [comment]
Oh, I should probably add a minimum version requirement for the FTB Mods haha
Didn't know that method was only added in later versions
That being said, glad to see that you've resolved this on your own, if anything comes up, feel free to just reopen this ^^
